/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SlotRecipe } from "./components/meal-plan-slot/meal-plan-slot";
import { RecipeInput } from "./components/recipe-form/recipe-form";
export { SlotRecipe } from "./components/meal-plan-slot/meal-plan-slot";
export { RecipeInput } from "./components/recipe-form/recipe-form";
export namespace Components {
    interface FilterPanel {
        /**
          * @default []
         */
        "categories": string[];
        /**
          * @default []
         */
        "selected": string[];
    }
    interface MealPlanSlot {
        "day": string;
        /**
          * @default null
         */
        "recipe": SlotRecipe | null;
    }
    interface RecipeCard {
        /**
          * @default false
         */
        "favorited": boolean;
        /**
          * @default ''
         */
        "image": string;
        "recipeId": string;
        "recipeTitle": string;
    }
    interface RecipeForm {
        /**
          * @default null
         */
        "initialValue": RecipeInput | null;
    }
    interface SearchBar {
        /**
          * @default 'Search recipes…'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface StarRating {
        /**
          * @default 5
         */
        "max": number;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default 0
         */
        "value": number;
    }
}
export interface FilterPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFilterPanelElement;
}
export interface MealPlanSlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealPlanSlotElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface RecipeFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeFormElement;
}
export interface SearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchBarElement;
}
export interface StarRatingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStarRatingElement;
}
declare global {
    interface HTMLFilterPanelElementEventMap {
        "filterChange": { selected: string[] };
    }
    interface HTMLFilterPanelElement extends Components.FilterPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFilterPanelElementEventMap>(type: K, listener: (this: HTMLFilterPanelElement, ev: FilterPanelCustomEvent<HTMLFilterPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFilterPanelElementEventMap>(type: K, listener: (this: HTMLFilterPanelElement, ev: FilterPanelCustomEvent<HTMLFilterPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFilterPanelElement: {
        prototype: HTMLFilterPanelElement;
        new (): HTMLFilterPanelElement;
    };
    interface HTMLMealPlanSlotElementEventMap {
        "recipeRemove": { day: string };
    }
    interface HTMLMealPlanSlotElement extends Components.MealPlanSlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealPlanSlotElementEventMap>(type: K, listener: (this: HTMLMealPlanSlotElement, ev: MealPlanSlotCustomEvent<HTMLMealPlanSlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealPlanSlotElementEventMap>(type: K, listener: (this: HTMLMealPlanSlotElement, ev: MealPlanSlotCustomEvent<HTMLMealPlanSlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealPlanSlotElement: {
        prototype: HTMLMealPlanSlotElement;
        new (): HTMLMealPlanSlotElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "favoriteToggle": { id: string };
    }
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeFormElementEventMap {
        "formSubmit": RecipeInput;
        "formCancel": void;
    }
    interface HTMLRecipeFormElement extends Components.RecipeForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeFormElement: {
        prototype: HTMLRecipeFormElement;
        new (): HTMLRecipeFormElement;
    };
    interface HTMLSearchBarElementEventMap {
        "searchSubmit": { query: string };
    }
    interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchBarElementEventMap>(type: K, listener: (this: HTMLSearchBarElement, ev: SearchBarCustomEvent<HTMLSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchBarElementEventMap>(type: K, listener: (this: HTMLSearchBarElement, ev: SearchBarCustomEvent<HTMLSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchBarElement: {
        prototype: HTMLSearchBarElement;
        new (): HTMLSearchBarElement;
    };
    interface HTMLStarRatingElementEventMap {
        "ratingChange": { value: number };
    }
    interface HTMLStarRatingElement extends Components.StarRating, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStarRatingElementEventMap>(type: K, listener: (this: HTMLStarRatingElement, ev: StarRatingCustomEvent<HTMLStarRatingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStarRatingElementEventMap>(type: K, listener: (this: HTMLStarRatingElement, ev: StarRatingCustomEvent<HTMLStarRatingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStarRatingElement: {
        prototype: HTMLStarRatingElement;
        new (): HTMLStarRatingElement;
    };
    interface HTMLElementTagNameMap {
        "filter-panel": HTMLFilterPanelElement;
        "meal-plan-slot": HTMLMealPlanSlotElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-form": HTMLRecipeFormElement;
        "search-bar": HTMLSearchBarElement;
        "star-rating": HTMLStarRatingElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface FilterPanel {
        /**
          * @default []
         */
        "categories"?: string[];
        "onFilterChange"?: (event: FilterPanelCustomEvent<{ selected: string[] }>) => void;
        /**
          * @default []
         */
        "selected"?: string[];
    }
    interface MealPlanSlot {
        "day": string;
        "onRecipeRemove"?: (event: MealPlanSlotCustomEvent<{ day: string }>) => void;
        /**
          * @default null
         */
        "recipe"?: SlotRecipe | null;
    }
    interface RecipeCard {
        /**
          * @default false
         */
        "favorited"?: boolean;
        /**
          * @default ''
         */
        "image"?: string;
        "onFavoriteToggle"?: (event: RecipeCardCustomEvent<{ id: string }>) => void;
        "recipeId": string;
        "recipeTitle": string;
    }
    interface RecipeForm {
        /**
          * @default null
         */
        "initialValue"?: RecipeInput | null;
        "onFormCancel"?: (event: RecipeFormCustomEvent<void>) => void;
        "onFormSubmit"?: (event: RecipeFormCustomEvent<RecipeInput>) => void;
    }
    interface SearchBar {
        "onSearchSubmit"?: (event: SearchBarCustomEvent<{ query: string }>) => void;
        /**
          * @default 'Search recipes…'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface StarRating {
        /**
          * @default 5
         */
        "max"?: number;
        "onRatingChange"?: (event: StarRatingCustomEvent<{ value: number }>) => void;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default 0
         */
        "value"?: number;
    }

    interface MealPlanSlotAttributes {
        "day": string;
    }
    interface RecipeCardAttributes {
        "recipeId": string;
        "recipeTitle": string;
        "image": string;
        "favorited": boolean;
    }
    interface SearchBarAttributes {
        "value": string;
        "placeholder": string;
    }
    interface StarRatingAttributes {
        "value": number;
        "max": number;
        "readonly": boolean;
    }

    interface IntrinsicElements {
        "filter-panel": FilterPanel;
        "meal-plan-slot": Omit<MealPlanSlot, keyof MealPlanSlotAttributes> & { [K in keyof MealPlanSlot & keyof MealPlanSlotAttributes]?: MealPlanSlot[K] } & { [K in keyof MealPlanSlot & keyof MealPlanSlotAttributes as `attr:${K}`]?: MealPlanSlotAttributes[K] } & { [K in keyof MealPlanSlot & keyof MealPlanSlotAttributes as `prop:${K}`]?: MealPlanSlot[K] } & OneOf<"day", MealPlanSlot["day"], MealPlanSlotAttributes["day"]>;
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] } & OneOf<"recipeId", RecipeCard["recipeId"], RecipeCardAttributes["recipeId"]> & OneOf<"recipeTitle", RecipeCard["recipeTitle"], RecipeCardAttributes["recipeTitle"]>;
        "recipe-form": RecipeForm;
        "search-bar": Omit<SearchBar, keyof SearchBarAttributes> & { [K in keyof SearchBar & keyof SearchBarAttributes]?: SearchBar[K] } & { [K in keyof SearchBar & keyof SearchBarAttributes as `attr:${K}`]?: SearchBarAttributes[K] } & { [K in keyof SearchBar & keyof SearchBarAttributes as `prop:${K}`]?: SearchBar[K] };
        "star-rating": Omit<StarRating, keyof StarRatingAttributes> & { [K in keyof StarRating & keyof StarRatingAttributes]?: StarRating[K] } & { [K in keyof StarRating & keyof StarRatingAttributes as `attr:${K}`]?: StarRatingAttributes[K] } & { [K in keyof StarRating & keyof StarRatingAttributes as `prop:${K}`]?: StarRating[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "filter-panel": LocalJSX.IntrinsicElements["filter-panel"] & JSXBase.HTMLAttributes<HTMLFilterPanelElement>;
            "meal-plan-slot": LocalJSX.IntrinsicElements["meal-plan-slot"] & JSXBase.HTMLAttributes<HTMLMealPlanSlotElement>;
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            "recipe-form": LocalJSX.IntrinsicElements["recipe-form"] & JSXBase.HTMLAttributes<HTMLRecipeFormElement>;
            "search-bar": LocalJSX.IntrinsicElements["search-bar"] & JSXBase.HTMLAttributes<HTMLSearchBarElement>;
            "star-rating": LocalJSX.IntrinsicElements["star-rating"] & JSXBase.HTMLAttributes<HTMLStarRatingElement>;
        }
    }
}
